sudo:
  required

dist:
  trusty

addons:
  apt:
    packages:
      - pandoc

language:
  python

python:
  - 2.7
  - 3.4
  - 3.5

env:
  global:
    - TOXENV="py${PYTHON_VERSION//./}"

install:
  - make install
  - pip install coveralls

script:
  - make test

after_success:
  - coveralls
